### PR TITLE
add http prometheus metrics

### LINKED ISSUE #2421: [new metrics] drone_http_response_code_[2/3/4/5]xx
`drone_http_response_code_2xx`

Type: counter

Purpose: tracks response code segments

Labels:
- endpoint
- specific code (200|etc)

---

`drone_http_response_code_3xx`

Type: counter

Purpose: tracks response code segments

Labels:
- endpoint
- specific code (304|etc)

---

`drone_http_response_code_4xx`

Type: counter

Purpose: tracks response code segments

Labels:
- endpoint
- specific code (401|404|etc)

---

`drone_http_response_code_5xx`

Type: counter

Purpose: tracks response code segments

Labels:
- endpoint
- specific code (500|502|etc)

### PR DESCRIPTION
**Pull request by maxknee**
This will add metrics to http endpoints to measure latency and to see if other parts of infra are working 

This will close #2421

### CODE REVIEW

**Review by tphoney — COMMENTED** [review]
I had a look at this, and based on the documentation for chi-prometheus: You add the middleware. But it looks like you need to add a handle for the endpoint to be active https://github.com/766b/chi-prometheus/blob/master/example/main.go#L23
Am i missing something from the documentation ?

**Comment by maxknee** [comment]
> I had a look at this, and based on the documentation for chi-prometheus: You add the middleware. But it looks like you need to add a handle for the endpoint to be active https://github.com/766b/chi-prometheus/blob/master/example/main.go#L23 Am i missing something from the documentation ?

Since there's already a `/metrics` endpoint, we don't need to add a handler. since chi will use that endpoint already:

running on a locally built version:

```
# HELP chi_requests_total How many HTTP requests processed, partitioned by status code, method and HTTP path.
# TYPE chi_requests_total counter
chi_requests_total{code="OK",method="GET",path="/",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/api/user",service="api"} 2
chi_requests_total{code="OK",method="GET",path="/api/user",service="server"} 2
chi_requests_total{code="OK",method="GET",path="/api/user/repos",service="api"} 1
chi_requests_total{code="OK",method="GET",path="/api/user/repos",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/favicon.png",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/favicon.png",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/manifest.json",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/manifest.json",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/static/css/2.abad2096.chunk.css",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/static/css/2.abad2096.chunk.css",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/static/css/main.3b0f8240.chunk.css",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/static/css/main.3b0f8240.chunk.css",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/static/js/2.ec852595.chunk.js",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/static/js/2.ec852595.chunk.js",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/static/js/main.316b22ac.chunk.js",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/static/js/main.316b22ac.chunk.js",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/static/media/Inter-Medium.18b8c68e.ttf",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/static/media/Inter-Medium.18b8c68e.ttf",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/static/media/Inter-Regular.9cd7588f.ttf",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/static/media/Inter-Regular.9cd7588f.ttf",service="web"} 1
chi_requests_total{code="OK",method="GET",path="/static/media/logo.76c744d4.svg",service="server"} 1
chi_requests_total{code="OK",method="GET",path="/static/media/logo.76c744d4.svg",service="web"} 1
```

**Comment by maxknee** [comment]
The metrics endpoint already declared: https://github.com/harness/gitness/pull/3432/files#diff-18f1f0e1c5973f4caeda8a50df35e925c9a92ffe265e7d77a75da01494188796R68

**Review by tphoney — APPROVED** [review]

**Comment by tphoney** [comment]
thanks @maxknee merged !!

**Comment by maxknee** [comment]
@tphoney do we have an idea when there will be a new release?

**Comment by tphoney** [comment]
> @tphoney do we have an idea when there will be a new release?

https://hub.docker.com/r/drone/drone/tags

**Comment by maxknee** [comment]
Oh wow. Awesome!

**Comment by pankdev** [comment]
Hi guys. I've learned about this amazing project, and while reviewing the release notes, I found this particular PR.

From what I can see, your project still uses a very old version of the Chi router, currently at version v5.0.12. This PR introduces a very outdated, abandoned dependency that lacks Go modules support. Moreover, these dependencies are based on an old version of Chi.

I might be misunderstanding this, but don't you think there could be issues with updating Chi because of this outdated dependency?

**Comment by xoxys** [comment]
@maxknee @tphoney This has flooded our Prometheus server with millions of metrics, causing massive performance issues. While we can drop and filter the chi metrics in Prometheus, enabling this by default without an option to disable it in drone might not be the best way. Would you consider adding an option to disable chi metrics in drone?

**Comment by maxknee** [comment]
> @maxknee @tphoney This has flooded our Prometheus server with millions of metrics, causing massive performance issues. While we can drop and filter the chi metrics in Prometheus, enabling this by default without an option to disable it in drone might not be the best way. Would you consider adding an option to disable chi metrics in drone?

Yes - working on optimizing it

**Comment by maxknee** [comment]
@xoxys I have this PR up: https://github.com/harness/gitness/pull/3451

**Pull request merged**
