### PR TITLE
Adding  Power (ppc64le) support

### PR DESCRIPTION
**Pull request by sumangalm-1**
https://github.com/harness/drone/issues/3245#issue-1327251205

### CODE REVIEW

**Comment by sumangalm-1** [comment]
@jimsheldon @jamesknowling, can you please review my PR ?

**Comment by bradrydzewski** [comment]
@sumangalm-1 while we appreciate the pull request, this cannot be merged because we would need ppc64le servers to build and publish a docker image.  Without ppc64le servers it would break our pipeline.

**Comment by sumangalm-1** [comment]
Thanks @bradrydzewski ,for responding . 
We can get an initial set of FREE ppc64le VMs at https://openpower.ic.unicamp.br/minicloud/.
If you need more ppc64le VM's then also we are ready to provide :).

**Comment by bradrydzewski** [comment]
last I recall, the servers at minicloud expire after a certain period of time which would cause periodic outages / break our pipeline and would be problematic.  We also need to use a hosting provider that is soc2 or fedramp certified, and I am not sure minicloud would qualify.

**Comment by sumangalm-1** [comment]
@bradrydzewski, I have connected with @jimsheldon. he has suggested using the Qemu user approach on x86.
If you want to test for a long time. then we will provide you with IBM cloud resources.

**Comment by bot2-harness** [comment]
This PR has been automatically closed due to inactivity.

**Pull request closed without merging**
