### PR TITLE
Multi Templates

### PR DESCRIPTION
**Pull request by badygin-yakov**
This is a new feature to Drone CI, allowing the use of multi templates. With this enhancement, users will have the capability to define and utilize multiple templates within their CI/CD pipelines. This is a significant addition that enhances the flexibility and extensibility of Drone CI, enabling users to streamline their pipeline definitions and improve overall workflow management.

### Changes Made
- Implemented the multi template functionality, enabling users to define and utilize multiple templates in their pipeline configuration.

### Benefits
- **Enhanced Reusability:** Multi templates empower users to encapsulate and reuse common pipeline segments across different projects and workflows, reducing redundancy and improving maintainability.
- **Customization:** Users can mix and match templates to tailor their CI/CD pipelines according to project-specific requirements, optimizing their workflows.

### Examples
template

```yaml
kind: pipeline
type: docker
name: {{ .input.name }}
steps:
  - name:  {{ upper .input.stepName }}
    image: {{ .input.image }}
    commands:
      - {{ .input.commands }}
```

drone.yaml
```yaml

kind: template
load: plugin.yaml
data:
  stepName: my_step
  image: my_image
  commands: my_command

---
kind: pipeline
type: docker
name: extra-pipeline
steps:
  - name:  extra_my_step
    image: extra_image
    commands:
      - echo "extra_command"

```
result pipeline 

```yaml
kind: pipeline
type: docker
name: defaults
steps:
  - name:  MY_STEP
    image: my_image
    commands:
      - my_command
---

kind: pipeline
type: docker
name: extra-pipeline
steps:
  - name:  extra_my_step
    image: extra_image
    commands:
      - echo "extra_command"
```

### CODE REVIEW

**Comment by tdavis96** [comment]
Can the template be (automatically) downloaded from a remote github repository, allowing for centralized administration and hosting of the template?

**Comment by badygin-yakov** [comment]
> Can the template be (automatically) downloaded from a remote github repository, allowing for centralized administration and hosting of the template?

Absolutely, the concept of fetching templates from remote repositories is indeed valuable. However, this particular pull request is focused on introducing multi templates within a single Drone file.

**Comment by alikhil** [comment]
@tphoney 
Any chance that this PR will be merged?

**Comment by bot2-harness** [comment]
This PR has been automatically closed due to inactivity.

**Pull request closed without merging**
