### PR TITLE
bugfix: drone component failed to run and the process could not be terminated normally

### PR DESCRIPTION
**Pull request by zc2638**
When the `drone` starts, if one of the coroutines fails to execute, it should exit the program.

Because `errgroup` is used, the program will only exit when all the coroutines have ended.

The fastest way to test is to let `drone server` listen an occupied port.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
Instead of removing errorgroup, I feel like we could fix with a small change to use `errgroup.WithContext`

> [`WithContext`](https://pkg.go.dev/golang.org/x/sync/errgroup#WithContext) returns a new Group and an associated Context derived from ctx.
> The derived Context is canceled the first time a function passed to Go returns a non-nil error or the first time Wait returns, whichever occurs first.

**Comment by zc2638** [comment]
> Instead of removing errgroup, I feel like we could fix with a small change to use `errgroup.WithContext`. When the derived context is cancelled it should cancel all remaining subroutines, since all of the subroutines accept context.

I agree with you. I'll revise it.

**Comment by zc2638** [comment]
@bradrydzewski Please take a look.

**Comment by bot2-harness** [comment]
This PR has been automatically closed due to inactivity.

**Pull request closed without merging**
